import { Incident } from './db-typings';

export const incidents: Incident[] = [
  { id: 1, name: 'Error en aplicación interna', category_id: 1, priority_id: 2 },
  { id: 2, name: 'Bug en nueva funcionalidad', category_id: 1, priority_id: 2 },
  { id: 3, name: 'Fallo en integración de APIs', category_id: 1, priority_id: 2 },
  { id: 4, name: 'Problemas con base de datos', category_id: 1, priority_id: 2 },
  { id: 5, name: 'Tiempo de respuesta lento en aplicación', category_id: 1, priority_id: 2 },
  { id: 6, name: 'Problemas en despliegue de software', category_id: 1, priority_id: 2 },
  { id: 7, name: 'Fallo en servidor', category_id: 2, priority_id: 2 },
  { id: 8, name: 'Espacio insuficiente en disco', category_id: 2, priority_id: 2 },
  { id: 9, name: 'Problemas con máquinas virtuales', category_id: 2, priority_id: 2 },
  { id: 10, name: 'Errores en sistema operativo', category_id: 2, priority_id: 2 },
  { id: 11, name: 'Falla en autenticación de usuario', category_id: 2, priority_id: 2 },
  { id: 12, name: 'Cuentas de usuario bloqueadas', category_id: 2, priority_id: 2 },
  { id: 13, name: 'Actualización de software requerida', category_id: 2, priority_id: 2 },
  { id: 14, name: 'Problema con impresoras', category_id: 3, priority_id: 2 },
  { id: 15, name: 'Fallo en acceso a correo electrónico', category_id: 3, priority_id: 2 },
  { id: 16, name: 'Error en software de ofimática', category_id: 3, priority_id: 2 },
  { id: 17, name: 'Reinicio inesperado de equipo', category_id: 3, priority_id: 2 },
  { id: 18, name: 'No funciona acceso remoto', category_id: 3, priority_id: 2 },
  { id: 19, name: 'Solicitud de instalación de software', category_id: 3, priority_id: 2 },
  { id: 20, name: 'Fallo en conexión a internet', category_id: 4, priority_id: 2 },
  { id: 21, name: 'Pérdida de paquetes en red', category_id: 4, priority_id: 2 },
  { id: 22, name: 'Problemas con VPN', category_id: 4, priority_id: 2 },
  { id: 23, name: 'Desempeño bajo en red interna', category_id: 4, priority_id: 2 },
  { id: 24, name: 'Acceso denegado a recursos compartidos', category_id: 4, priority_id: 2 },
  { id: 25, name: 'Caída de switch o router', category_id: 4, priority_id: 2 },
  { id: 26, name: 'Solicitud de nueva conexión de red', category_id: 4, priority_id: 2 },
];
