import { IncidentTicket } from "./db-typings";

export const incidentTiceks: IncidentTicket[] = [
  {
    id: 1,
    id_employee_creator: 9,
    id_employee_owner: 9,
    id_incident: 3,
    description: 'Fallo en integración de APIs en sistema contable.',
    id_current_history: 1,
    created_at: new Date("2025-03-28T00:15:00Z"),
  },
  {
    id: 2,
    id_employee_creator: 10,
    id_employee_owner: 10,
    id_incident: 7,
    description: 'El servidor de producción dejó de responder.',
    id_current_history: 2,
    created_at: new Date("2025-03-28T03:30:00Z"),
  },
  {
    id: 3,
    id_employee_creator: 11,
    id_employee_owner: 11,
    id_incident: 12,
    description: 'Varios usuarios tienen sus cuentas bloqueadas.',
    id_current_history: 3,
    created_at: new Date("2025-03-28T06:45:00Z"),
  },
  {
    id: 4,
    id_employee_creator: 12,
    id_employee_owner: 12,
    id_incident: 15,
    description: 'No se puede acceder al correo electrónico.',
    id_current_history: 4,
    created_at: new Date("2025-03-28T09:00:00Z"),
  },
  {
    id: 5,
    id_employee_creator: 13,
    id_employee_owner: 13,
    id_incident: 19,
    description: 'Se requiere instalación de software especializado.',
    id_current_history: 5,
    created_at: new Date("2025-03-28T12:15:00Z"),
  },
  {
    id: 6,
    id_employee_creator: 9,
    id_employee_owner: 9,
    id_incident: 22,
    description: 'Problemas intermitentes con la VPN.',
    id_current_history: 6,
    created_at: new Date("2025-03-28T15:30:00Z"),
  },
  {
    id: 7,
    id_employee_creator: 10,
    id_employee_owner: 10,
    id_incident: 25,
    description: 'Caída repentina de un switch en la oficina.',
    id_current_history: 7,
    created_at: new Date("2025-03-28T18:45:00Z"),
  },
  {
    id: 8,
    id_employee_creator: 11,
    id_employee_owner: 11,
    id_incident: 5,
    description: 'La aplicación interna tiene tiempos de respuesta muy lentos.',
    id_current_history: 8,
    created_at: new Date("2025-03-28T21:00:00Z"),
  },
  {
    id: 9,
    id_employee_creator: 12,
    id_employee_owner: 12,
    id_incident: 10,
    description: 'Errores frecuentes en el sistema operativo del servidor.',
    id_current_history: 9,
    created_at: new Date("2025-03-28T23:15:00Z"),
  },
  {
    id: 10,
    id_employee_creator: 13,
    id_employee_owner: 13,
    id_incident: 26,
    description: 'Se requiere una nueva conexión de red en la oficina.',
    id_current_history: 10,
    created_at: new Date("2025-03-28T13:45:00Z"),
  },
];
